// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using GoldBusiness.Data;
using APIGoldBusiness.Data;

namespace GoldBusiness.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20201125000144_Added Custom Properties")]
    partial class AddedCustomProperties
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("GoldBusiness.Models.Actividad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Cancelado")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(2)")
                        .HasMaxLength(2);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasName("IX_Actividad");

                    b.ToTable("Actividad");
                });

            modelBuilder.Entity("GoldBusiness.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Apellidos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Entidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Establecimiento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Nombres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<byte[]>("ProfilePicture")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Unidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<int>("UsernameChangeLimit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("GoldBusiness.Models.BinTarjeta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bin")
                        .IsRequired()
                        .HasColumnType("nvarchar(16)")
                        .HasMaxLength(16);

                    b.Property<bool>("Cancelado")
                        .HasColumnType("bit");

                    b.Property<int>("CuentaBanco")
                        .HasColumnType("int");

                    b.Property<int>("CuentaComision")
                        .HasColumnType("int");

                    b.Property<int>("CuentaEfecto")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CuentaBanco");

                    b.HasIndex("CuentaComision");

                    b.HasIndex("CuentaEfecto");

                    b.HasIndex("Tipo");

                    b.HasIndex("Bin", "Cancelado")
                        .HasName("IX_BinTarjeta");

                    b.HasIndex("Bin", "Tipo")
                        .HasName("IX_BinTarjeta_TipoTarjeta");

                    b.ToTable("BinTarjeta");
                });

            modelBuilder.Entity("GoldBusiness.Models.CertificadoComercial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Cancelado")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("Descripcion", "Cancelado")
                        .HasName("IX_CertificadoComercial");

                    b.ToTable("CertificadoComercial");
                });

            modelBuilder.Entity("GoldBusiness.Models.ClasificadorAnuncios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Cancelado")
                        .HasColumnType("bit");

                    b.Property<string>("ClasificadorAnuncio")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("ClasificadorAnuncio", "Cancelado")
                        .IsUnique()
                        .HasName("IX_ClasificadorAnuncios");

                    b.ToTable("ClasificadorAnuncios");
                });

            modelBuilder.Entity("GoldBusiness.Models.Cuenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Cancelado")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(8)")
                        .HasMaxLength(8);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("Codigo", "Cancelado")
                        .IsUnique()
                        .HasName("IX_Cuenta");

                    b.ToTable("Cuenta");
                });

            modelBuilder.Entity("GoldBusiness.Models.Efemerides", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Cancelado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("date");

                    b.Property<string>("HechoHistorico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Efemerides");
                });

            modelBuilder.Entity("GoldBusiness.Models.Entidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<bool>("Cancelado")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(5)")
                        .HasMaxLength(5);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono1")
                        .HasColumnName("Telefono_1")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Telefono2")
                        .HasColumnName("Telefono_2")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Telefono3")
                        .HasColumnName("Telefono_3")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("TelefonoVozIp")
                        .HasColumnName("Telefono_VozIp")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("Codigo", "Activo", "Cancelado")
                        .IsUnique()
                        .HasName("IX_Entidad");

                    b.ToTable("Entidad");
                });

            modelBuilder.Entity("GoldBusiness.Models.Establecimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<bool>("Cancelado")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(2)")
                        .HasMaxLength(2);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Entidad")
                        .HasColumnType("int");

                    b.Property<string>("Telefono1")
                        .HasColumnName("Telefono_1")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Telefono2")
                        .HasColumnName("Telefono_2")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Telefono3")
                        .HasColumnName("Telefono_3")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("TelefonoVozIp")
                        .HasColumnName("Telefono_VozIp")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("Entidad");

                    b.HasIndex("Codigo", "Entidad", "Activo", "Cancelado")
                        .IsUnique()
                        .HasName("IX_Establecimiento");

                    b.ToTable("Establecimiento");
                });

            modelBuilder.Entity("GoldBusiness.Models.MaskRed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CantidadHost")
                        .HasColumnType("bigint");

                    b.Property<int>("Mask")
                        .HasColumnType("int");

                    b.Property<string>("MaskSubred")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.HasKey("Id");

                    b.ToTable("MaskRed");
                });

            modelBuilder.Entity("GoldBusiness.Models.Moneda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Cancelado")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(3)")
                        .HasMaxLength(3);

                    b.HasKey("Id");

                    b.HasIndex("Descripcion")
                        .IsUnique()
                        .HasName("IX_Moneda");

                    b.ToTable("Moneda");
                });

            modelBuilder.Entity("GoldBusiness.Models.PlanVenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal?>("Abril")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("Actividad")
                        .HasColumnType("int");

                    b.Property<decimal?>("Agosto")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<bool>("Cancelado")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Diciembre")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("Enero")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("Febrero")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("Julio")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("Junio")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("Marzo")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("Mayo")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("Moneda")
                        .HasColumnType("int");

                    b.Property<decimal?>("Noviembre")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("Octubre")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("Septiembre")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("Unidad")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Actividad");

                    b.HasIndex("Moneda");

                    b.HasIndex("Unidad", "Moneda", "Actividad")
                        .IsUnique()
                        .HasName("IX_PlanVenta");

                    b.ToTable("PlanVenta");
                });

            modelBuilder.Entity("GoldBusiness.Models.PlanVentaCombustible", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<decimal>("Agricultura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValueSql("((0))");

                    b.Property<bool>("Cancelado")
                        .HasColumnType("bit");

                    b.Property<decimal>("Estatal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValueSql("((0))");

                    b.Property<int>("PlanVenta")
                        .HasColumnType("int");

                    b.Property<decimal>("Privado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValueSql("((0))");

                    b.Property<decimal>("Transportista")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValueSql("((0))");

                    b.HasKey("Id");

                    b.HasIndex("PlanVenta")
                        .IsUnique()
                        .HasName("IX_PlanVentaCombustible");

                    b.ToTable("PlanVentaCombustible");
                });

            modelBuilder.Entity("GoldBusiness.Models.TipoPos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Cancelado")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.HasKey("Id");

                    b.HasIndex("Descripcion")
                        .IsUnique()
                        .HasName("IX_TipoPos");

                    b.ToTable("TipoPos");
                });

            modelBuilder.Entity("GoldBusiness.Models.TipoTarjeta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Cancelado")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("Descripcion", "Cancelado")
                        .HasName("IX_TipoTarjeta");

                    b.ToTable("TipoTarjeta");
                });

            modelBuilder.Entity("GoldBusiness.Models.Unidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Actividad")
                        .HasColumnType("int");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<bool>("Cancelado")
                        .HasColumnType("bit");

                    b.Property<string>("Cliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(8)")
                        .HasMaxLength(8);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(3)")
                        .HasMaxLength(3);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Establecimiento")
                        .HasColumnType("int");

                    b.Property<bool>("Principal")
                        .HasColumnType("bit");

                    b.Property<string>("Telefono1")
                        .HasColumnName("Telefono_1")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Telefono2")
                        .HasColumnName("Telefono_2")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Telefono3")
                        .HasColumnName("Telefono_3")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("TelefonoVozIp")
                        .HasColumnName("Telefono_VozIp")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("Actividad");

                    b.HasIndex("Cliente")
                        .IsUnique();

                    b.HasIndex("Establecimiento");

                    b.HasIndex("Codigo", "Establecimiento", "Activo", "Cancelado")
                        .IsUnique()
                        .HasName("IX_Unidad");

                    b.ToTable("Unidad");
                });

            modelBuilder.Entity("GoldBusiness.Models.UnidadTCs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Cancelado")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(6)")
                        .HasMaxLength(6);

                    b.Property<int>("Moneda")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<int>("Unidad")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("Moneda");

                    b.HasIndex("Unidad");

                    b.HasIndex("Tipo", "Moneda", "Unidad")
                        .IsUnique()
                        .HasName("IX_UnidadTCs");

                    b.ToTable("UnidadTCs");
                });

            modelBuilder.Entity("GoldBusiness.Models.UnidadUNE", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Cancelado")
                        .HasColumnType("bit");

                    b.Property<string>("Cliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(6)")
                        .HasMaxLength(6);

                    b.Property<string>("Contador")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("Crf")
                        .IsRequired()
                        .HasColumnName("CRF")
                        .HasColumnType("nvarchar(7)")
                        .HasMaxLength(7);

                    b.Property<string>("Folio")
                        .IsRequired()
                        .HasColumnType("nvarchar(2)")
                        .HasMaxLength(2);

                    b.Property<string>("OficinaComercial")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.Property<string>("Ruta")
                        .IsRequired()
                        .HasColumnType("nvarchar(2)")
                        .HasMaxLength(2);

                    b.Property<int>("Unidad")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Cliente")
                        .IsUnique();

                    b.HasIndex("Contador")
                        .IsUnique();

                    b.HasIndex("Crf")
                        .IsUnique();

                    b.HasIndex("Folio")
                        .IsUnique();

                    b.HasIndex("Ruta")
                        .IsUnique();

                    b.HasIndex("Unidad")
                        .IsUnique();

                    b.ToTable("UnidadUNE");
                });

            modelBuilder.Entity("GoldBusiness.Models.ZonaRed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<bool>("Cancelado")
                        .HasColumnType("bit");

                    b.Property<string>("Enlace")
                        .HasColumnType("nvarchar(7)")
                        .HasMaxLength(7);

                    b.Property<string>("Interface")
                        .HasColumnType("nvarchar(6)")
                        .HasMaxLength(6);

                    b.Property<string>("LocalLan")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.Property<int>("LocalLanMask")
                        .HasColumnType("int");

                    b.Property<string>("SegmentoLan")
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.Property<int?>("SegmentoLanMask")
                        .HasColumnType("int");

                    b.Property<string>("SegmentoWan")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.Property<int>("SegmentoWanMask")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("TipoRoute")
                        .HasColumnType("nvarchar(16)")
                        .HasMaxLength(16);

                    b.Property<string>("TunelWan")
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.Property<int?>("TunelWanMask")
                        .HasColumnType("int");

                    b.Property<int>("Unidad")
                        .HasColumnType("int");

                    b.Property<string>("Velocidad")
                        .HasColumnType("nvarchar(12)")
                        .HasMaxLength(12);

                    b.Property<string>("Vpn")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.HasKey("Id");

                    b.HasIndex("LocalLan")
                        .IsUnique();

                    b.HasIndex("LocalLanMask");

                    b.HasIndex("SegmentoLan")
                        .IsUnique()
                        .HasFilter("[SegmentoLan] IS NOT NULL");

                    b.HasIndex("SegmentoLanMask");

                    b.HasIndex("SegmentoWan")
                        .IsUnique();

                    b.HasIndex("SegmentoWanMask");

                    b.HasIndex("TunelWan")
                        .IsUnique()
                        .HasFilter("[TunelWan] IS NOT NULL");

                    b.HasIndex("TunelWanMask");

                    b.HasIndex("Unidad")
                        .IsUnique()
                        .HasName("IX_ZonaRed");

                    b.ToTable("ZonaRed");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("GoldBusiness.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("GoldBusiness.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GoldBusiness.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("GoldBusiness.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GoldBusiness.Models.BinTarjeta", b =>
                {
                    b.HasOne("GoldBusiness.Models.Cuenta", "CuentaBancoNavigation")
                        .WithMany("BinTarjetaCuentaBancoNavigation")
                        .HasForeignKey("CuentaBanco")
                        .HasConstraintName("FK_BinTarjeta_CuentaBanco")
                        .IsRequired();

                    b.HasOne("GoldBusiness.Models.Cuenta", "CuentaComisionNavigation")
                        .WithMany("BinTarjetaCuentaComisionNavigation")
                        .HasForeignKey("CuentaComision")
                        .HasConstraintName("FK_BinTarjeta_CuentaComision")
                        .IsRequired();

                    b.HasOne("GoldBusiness.Models.Cuenta", "CuentaEfectoNavigation")
                        .WithMany("BinTarjetaCuentaEfectoNavigation")
                        .HasForeignKey("CuentaEfecto")
                        .HasConstraintName("FK_BinTarjeta_CuentaEfecto")
                        .IsRequired();

                    b.HasOne("GoldBusiness.Models.TipoTarjeta", "TipoNavigation")
                        .WithMany("BinTarjeta")
                        .HasForeignKey("Tipo")
                        .HasConstraintName("FK_BinTarjetas_TipoTarjeta")
                        .IsRequired();
                });

            modelBuilder.Entity("GoldBusiness.Models.Establecimiento", b =>
                {
                    b.HasOne("GoldBusiness.Models.Entidad", "EntidadNavigation")
                        .WithMany("Establecimiento")
                        .HasForeignKey("Entidad")
                        .HasConstraintName("FK_Establecimiento_Entidad")
                        .IsRequired();
                });

            modelBuilder.Entity("GoldBusiness.Models.PlanVenta", b =>
                {
                    b.HasOne("GoldBusiness.Models.Actividad", "ActividadNavigation")
                        .WithMany("PlanVenta")
                        .HasForeignKey("Actividad")
                        .HasConstraintName("FK_PlanVenta_Actividad")
                        .IsRequired();

                    b.HasOne("GoldBusiness.Models.Moneda", "MonedaNavigation")
                        .WithMany("PlanVenta")
                        .HasForeignKey("Moneda")
                        .HasConstraintName("FK_PlanVenta_Moneda")
                        .IsRequired();

                    b.HasOne("GoldBusiness.Models.Unidad", "UnidadNavigation")
                        .WithMany("PlanVenta")
                        .HasForeignKey("Unidad")
                        .HasConstraintName("FK_PlanVenta_Unidad")
                        .IsRequired();
                });

            modelBuilder.Entity("GoldBusiness.Models.PlanVentaCombustible", b =>
                {
                    b.HasOne("GoldBusiness.Models.PlanVenta", "PlanVentaNavigation")
                        .WithOne("PlanVentaCombustible")
                        .HasForeignKey("GoldBusiness.Models.PlanVentaCombustible", "PlanVenta")
                        .HasConstraintName("FK_PlanVentaCombustible_PlanVenta")
                        .IsRequired();
                });

            modelBuilder.Entity("GoldBusiness.Models.Unidad", b =>
                {
                    b.HasOne("GoldBusiness.Models.Actividad", "ActividadNavigation")
                        .WithMany("Unidad")
                        .HasForeignKey("Actividad")
                        .HasConstraintName("FK_Unidad_Actividad")
                        .IsRequired();

                    b.HasOne("GoldBusiness.Models.Establecimiento", "EstablecimientoNavigation")
                        .WithMany("Unidad")
                        .HasForeignKey("Establecimiento")
                        .HasConstraintName("FK_Unidad_Establecimiento")
                        .IsRequired();
                });

            modelBuilder.Entity("GoldBusiness.Models.UnidadTCs", b =>
                {
                    b.HasOne("GoldBusiness.Models.Moneda", "MonedaNavigation")
                        .WithMany("UnidadTCs")
                        .HasForeignKey("Moneda")
                        .HasConstraintName("FK_UnidadTCs_Moneda")
                        .IsRequired();

                    b.HasOne("GoldBusiness.Models.TipoPos", "TipoNavigation")
                        .WithMany("UnidadTCs")
                        .HasForeignKey("Tipo")
                        .HasConstraintName("FK_UnidadTCs_TipoPos")
                        .IsRequired();

                    b.HasOne("GoldBusiness.Models.Unidad", "UnidadNavigation")
                        .WithMany("UnidadTCs")
                        .HasForeignKey("Unidad")
                        .HasConstraintName("FK_UnidadTCs_Unidad")
                        .IsRequired();
                });

            modelBuilder.Entity("GoldBusiness.Models.UnidadUNE", b =>
                {
                    b.HasOne("GoldBusiness.Models.Unidad", "UnidadNavigation")
                        .WithOne("UnidadUNE")
                        .HasForeignKey("GoldBusiness.Models.UnidadUNE", "Unidad")
                        .HasConstraintName("FK_UnidadUNE_Unidad")
                        .IsRequired();
                });

            modelBuilder.Entity("GoldBusiness.Models.ZonaRed", b =>
                {
                    b.HasOne("GoldBusiness.Models.MaskRed", "LocalLanMaskNavigation")
                        .WithMany("ZonaRedLocalLanMaskNavigation")
                        .HasForeignKey("LocalLanMask")
                        .HasConstraintName("FK_ZonaRed_MaskRed3")
                        .IsRequired();

                    b.HasOne("GoldBusiness.Models.MaskRed", "SegmentoLanMaskNavigation")
                        .WithMany("ZonaRedSegmentoLanMaskNavigation")
                        .HasForeignKey("SegmentoLanMask")
                        .HasConstraintName("FK_ZonaRed_MaskRed1");

                    b.HasOne("GoldBusiness.Models.MaskRed", "SegmentoWanMaskNavigation")
                        .WithMany("ZonaRedSegmentoWanMaskNavigation")
                        .HasForeignKey("SegmentoWanMask")
                        .HasConstraintName("FK_ZonaRed_MaskRed")
                        .IsRequired();

                    b.HasOne("GoldBusiness.Models.MaskRed", "TunelWanMaskNavigation")
                        .WithMany("ZonaRedTunelWanMaskNavigation")
                        .HasForeignKey("TunelWanMask")
                        .HasConstraintName("FK_ZonaRed_MaskRed2");

                    b.HasOne("GoldBusiness.Models.Unidad", "UnidadNavigation")
                        .WithOne("ZonaRed")
                        .HasForeignKey("GoldBusiness.Models.ZonaRed", "Unidad")
                        .HasConstraintName("FK_ZonaRed_Unidad")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
