// <auto-generated />
using System;
using APIGoldBusiness.Data;
using GoldBusiness.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GoldBusiness.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230701141518_Update-30-06-2023")]
    partial class Update30062023
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GoldBusiness.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Acceso_1")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("Acceso_2")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("Acceso_3")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Apellidos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ChangePassword")
                        .HasColumnType("bit");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Nombres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<byte[]>("ProfilePicture")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("UsernameChangeLimit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("GoldBusiness.Models.CajaRegistradora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Cerrado")
                        .HasColumnType("bit");

                    b.Property<int>("IdTurno")
                        .HasColumnType("int");

                    b.Property<int?>("Mesa")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdTurno");

                    b.ToTable("CajaRegistradora");
                });

            modelBuilder.Entity("GoldBusiness.Models.CajaRegistradoraDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CajaRegistradora")
                        .HasColumnType("int");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal>("ImporteVenta")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("Localidad")
                        .HasColumnType("int");

                    b.Property<int>("Producto")
                        .HasColumnType("int");

                    b.Property<decimal>("Venta")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("CajaRegistradora");

                    b.ToTable("CajaRegistradoraDetalle");
                });

            modelBuilder.Entity("GoldBusiness.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BicoSwift")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<bool>("Cancelado")
                        .HasColumnType("bit");

                    b.Property<string>("CodPostal")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Email1")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("email1");

                    b.Property<string>("Email2")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("email2");

                    b.Property<string>("Fax1")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Fax2")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaHoraCreado")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("FechaHoraModificado")
                        .HasColumnType("datetime");

                    b.Property<string>("Iban")
                        .HasMaxLength(27)
                        .HasColumnType("nvarchar(27)");

                    b.Property<decimal>("Iva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(4, 2)")
                        .HasDefaultValueSql("((0.00))");

                    b.Property<string>("ModificadoPor")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Municipio")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nif")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Provincia")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telefono1")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telefono2")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Web")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo", "Cancelado")
                        .IsUnique()
                        .HasDatabaseName("IX_Cliente");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("GoldBusiness.Models.Comprobante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Automatico")
                        .HasColumnType("bit");

                    b.Property<bool>("Cancelado")
                        .HasColumnType("bit");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Establecimiento")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaHoraCreado")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("FechaHoraModificado")
                        .HasColumnType("datetime");

                    b.Property<string>("ModificadoPor")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NoComprobante")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("Posteado")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Establecimiento");

                    b.ToTable("Comprobante");
                });

            modelBuilder.Entity("GoldBusiness.Models.ComprobanteDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Cancelado")
                        .HasColumnType("bit");

                    b.Property<int>("Comprobante")
                        .HasColumnType("int");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<decimal>("Credito")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("Cuenta")
                        .HasColumnType("int");

                    b.Property<decimal>("Debito")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Departamento")
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<DateTime>("FechaHoraCreado")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("FechaHoraModificado")
                        .HasColumnType("datetime");

                    b.Property<string>("ModificadoPor")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Nota")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Comprobante");

                    b.HasIndex("Cuenta");

                    b.ToTable("ComprobanteDetalle");
                });

            modelBuilder.Entity("GoldBusiness.Models.ComprobanteTemporal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoTransaccion")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<decimal?>("Credito")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Cuenta")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<decimal?>("Debito")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Departamento")
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Establecimiento")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("date");

                    b.Property<bool>("Inventario")
                        .HasColumnType("bit");

                    b.Property<string>("NoDocumento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Transaccion")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Establecimiento");

                    b.ToTable("ComprobanteTemporal");
                });

            modelBuilder.Entity("GoldBusiness.Models.ConceptoAjuste", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Cancelado")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Cuenta")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("FechaHoraCreado")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("FechaHoraModificado")
                        .HasColumnType("datetime");

                    b.Property<string>("ModificadoPor")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Cuenta");

                    b.HasIndex("Codigo", "Cancelado")
                        .IsUnique()
                        .HasDatabaseName("IX_ConceptoAjuste");

                    b.ToTable("ConceptoAjuste");
                });

            modelBuilder.Entity("GoldBusiness.Models.Configuracion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Caducidad")
                        .HasColumnType("date");

                    b.Property<string>("CodPostal")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("CodigoSistema")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CuentaCobrar")
                        .HasColumnType("int");

                    b.Property<int>("CuentaPagar")
                        .HasColumnType("int");

                    b.Property<string>("Direccion")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Licencia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Municipio")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NombreNegocio")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Provincia")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Web")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("CuentaCobrar");

                    b.HasIndex("CuentaPagar");

                    b.ToTable("Configuracion");
                });

            modelBuilder.Entity("GoldBusiness.Models.Cuenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Cancelado")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("FechaHoraCreado")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("FechaHoraModificado")
                        .HasColumnType("datetime");

                    b.Property<string>("ModificadoPor")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("SubGrupoCuenta")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubGrupoCuenta")
                        .HasDatabaseName("IX_Cuenta_SubGrupo");

                    b.HasIndex("Codigo", "SubGrupoCuenta", "Cancelado")
                        .IsUnique()
                        .HasDatabaseName("IX_Cuenta");

                    b.ToTable("Cuenta");
                });

            modelBuilder.Entity("GoldBusiness.Models.CuentaCobrarPagar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Cancelado")
                        .HasColumnType("bit");

                    b.Property<int?>("Cliente")
                        .HasColumnType("int");

                    b.Property<bool>("Contabilizada")
                        .HasColumnType("bit");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("CuentaCobro")
                        .HasColumnType("int");

                    b.Property<int?>("CuentaPago")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaHoraCreado")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("FechaHoraModificado")
                        .HasColumnType("datetime");

                    b.Property<decimal>("Importe")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("Localidad")
                        .HasColumnType("int");

                    b.Property<string>("ModificadoPor")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NoDocumento")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NoPrimario")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Proveedor")
                        .HasColumnType("int");

                    b.Property<int>("Transaccion")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Cliente");

                    b.HasIndex("CuentaCobro");

                    b.HasIndex("CuentaPago");

                    b.HasIndex("Localidad");

                    b.HasIndex("Proveedor");

                    b.HasIndex("Transaccion");

                    b.ToTable("CuentaCobrarPagar");
                });

            modelBuilder.Entity("GoldBusiness.Models.ErroresVenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("numeric(18, 2)");

                    b.Property<int>("Codigo")
                        .HasColumnType("int");

                    b.Property<decimal>("Costo")
                        .HasColumnType("numeric(18, 2)");

                    b.Property<decimal>("ImporteCosto")
                        .HasColumnType("numeric(18, 2)");

                    b.Property<int>("Localidad")
                        .HasColumnType("int");

                    b.Property<int>("OperacionesDetalle")
                        .HasColumnType("int");

                    b.Property<bool>("Servicio")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("ErroresVenta");
                });

            modelBuilder.Entity("GoldBusiness.Models.Establecimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<bool>("Cancelado")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("FechaHoraCreado")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("FechaHoraModificado")
                        .HasColumnType("datetime");

                    b.Property<string>("ModificadoPor")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Negocio")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Negocio", "Codigo", "Cancelado")
                        .IsUnique()
                        .HasDatabaseName("IX_Establecimiento");

                    b.ToTable("Establecimiento");
                });

            modelBuilder.Entity("GoldBusiness.Models.EstadoCuenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cuenta")
                        .HasColumnType("int");

                    b.Property<string>("Departamento")
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<int>("Establecimiento")
                        .HasColumnType("int");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("Establecimiento");

                    b.HasIndex("Cuenta", "Departamento")
                        .IsUnique()
                        .HasDatabaseName("IX_EstadoCuenta")
                        .HasFilter("[Departamento] IS NOT NULL");

                    b.ToTable("EstadoCuenta");
                });

            modelBuilder.Entity("GoldBusiness.Models.FichaProducto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Cancelado")
                        .HasColumnType("bit");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("numeric(18, 3)");

                    b.Property<int>("Codigo")
                        .HasColumnType("int");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("FechaHoraCreado")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("FechaHoraModificado")
                        .HasColumnType("datetime");

                    b.Property<int>("Localidad")
                        .HasColumnType("int");

                    b.Property<string>("ModificadoPor")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Producto")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Codigo");

                    b.HasIndex("Localidad");

                    b.HasIndex("Producto");

                    b.ToTable("FichaProducto");
                });

            modelBuilder.Entity("GoldBusiness.Models.GrupoCuenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Cancelado")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("FechaHoraCreado")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("FechaHoraModificado")
                        .HasColumnType("datetime");

                    b.Property<string>("ModificadoPor")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Descripcion", "Cancelado")
                        .IsUnique()
                        .HasDatabaseName("IX_GrupoCuenta");

                    b.ToTable("GrupoCuenta");
                });

            modelBuilder.Entity("GoldBusiness.Models.IdTurno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cajero")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("Cierre")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("Extraccion")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("date");

                    b.Property<decimal?>("Fondo")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("IdTurno");
                });

            modelBuilder.Entity("GoldBusiness.Models.Linea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Cancelado")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("FechaHoraCreado")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("FechaHoraModificado")
                        .HasColumnType("datetime");

                    b.Property<string>("ModificadoPor")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo", "Cancelado")
                        .IsUnique()
                        .HasDatabaseName("IX_Linea");

                    b.ToTable("Linea");
                });

            modelBuilder.Entity("GoldBusiness.Models.Localidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<bool>("Almacen")
                        .HasColumnType("bit");

                    b.Property<bool>("Cancelado")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("CuentaCosto")
                        .HasColumnType("int");

                    b.Property<int>("CuentaDevolucion")
                        .HasColumnType("int");

                    b.Property<int>("CuentaInventario")
                        .HasColumnType("int");

                    b.Property<int>("CuentaVenta")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Establecimiento")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaHoraCreado")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("FechaHoraModificado")
                        .HasColumnType("datetime");

                    b.Property<string>("ModificadoPor")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("CuentaCosto");

                    b.HasIndex("CuentaDevolucion");

                    b.HasIndex("CuentaInventario");

                    b.HasIndex("CuentaVenta");

                    b.HasIndex("Establecimiento", "Codigo", "Cancelado")
                        .IsUnique()
                        .HasDatabaseName("IX_Localidad");

                    b.ToTable("Localidad");
                });

            modelBuilder.Entity("GoldBusiness.Models.Moneda", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("Cancelado")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Establecimiento")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaHoraCreado")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("FechaHoraModificado")
                        .HasColumnType("datetime");

                    b.Property<string>("ModificadoPor")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Establecimiento", "Codigo", "Cancelado")
                        .IsUnique()
                        .HasDatabaseName("IX_Moneda");

                    b.ToTable("Moneda");
                });

            modelBuilder.Entity("GoldBusiness.Models.OperacionesDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Cancelado")
                        .HasColumnType("bit");

                    b.Property<decimal>("Cantidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18, 3)")
                        .HasDefaultValueSql("((0.00))");

                    b.Property<int>("Codigo")
                        .HasColumnType("int");

                    b.Property<decimal>("Costo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18, 2)")
                        .HasDefaultValueSql("((0.00))");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<decimal>("Existencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18, 3)")
                        .HasDefaultValueSql("((0.00))");

                    b.Property<DateTime>("FechaHoraCreado")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("FechaHoraModificado")
                        .HasColumnType("datetime");

                    b.Property<decimal>("ImporteCosto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18, 2)")
                        .HasDefaultValueSql("((0.00))");

                    b.Property<decimal>("ImporteVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18, 2)")
                        .HasDefaultValueSql("((0.00))");

                    b.Property<int>("Localidad")
                        .HasColumnType("int");

                    b.Property<string>("ModificadoPor")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("OperacionesEncabezado")
                        .HasColumnType("int");

                    b.Property<decimal>("Venta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18, 2)")
                        .HasDefaultValueSql("((0.00))");

                    b.HasKey("Id");

                    b.HasIndex("Codigo");

                    b.HasIndex("Localidad");

                    b.HasIndex("OperacionesEncabezado");

                    b.ToTable("OperacionesDetalle");
                });

            modelBuilder.Entity("GoldBusiness.Models.OperacionesEncabezado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Cancelado")
                        .HasColumnType("bit");

                    b.Property<int?>("Cliente")
                        .HasColumnType("int");

                    b.Property<string>("Concepto")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ConceptoAjuste")
                        .HasColumnType("int");

                    b.Property<bool>("Contabilizada")
                        .HasColumnType("bit");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("Efectivo")
                        .HasColumnType("bit");

                    b.Property<int>("Establecimiento")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaHoraCreado")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("FechaHoraModificado")
                        .HasColumnType("datetime");

                    b.Property<string>("ModificadoPor")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NoDocumento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NoPrimario")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Proveedor")
                        .HasColumnType("int");

                    b.Property<int?>("Referencia")
                        .HasColumnType("int");

                    b.Property<int>("Transaccion")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Cliente");

                    b.HasIndex("ConceptoAjuste");

                    b.HasIndex("Proveedor");

                    b.HasIndex("Transaccion");

                    b.HasIndex("Establecimiento", "Transaccion", "NoDocumento", "Cancelado")
                        .IsUnique()
                        .HasDatabaseName("IX_OperacionesEncabezado");

                    b.ToTable("OperacionesEncabezado");
                });

            modelBuilder.Entity("GoldBusiness.Models.OperacionesServicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Cancelado")
                        .HasColumnType("bit");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("numeric(18, 2)");

                    b.Property<int>("Codigo")
                        .HasColumnType("int");

                    b.Property<decimal>("Costo")
                        .HasColumnType("numeric(18, 2)");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("FechaHoraCreado")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("FechaHoraModificado")
                        .HasColumnType("datetime");

                    b.Property<decimal>("ImporteCosto")
                        .HasColumnType("numeric(18, 2)");

                    b.Property<int>("Localidad")
                        .HasColumnType("int");

                    b.Property<string>("ModificadoPor")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("OperacionesDetalle")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OperacionesDetalle");

                    b.ToTable("OperacionesServicio");
                });

            modelBuilder.Entity("GoldBusiness.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Cancelado")
                        .HasColumnType("bit");

                    b.Property<string>("Caracteristicas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("CodigoReferencia")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Establecimiento")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaHoraCreado")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("FechaHoraModificado")
                        .HasColumnType("datetime");

                    b.Property<byte[]>("Imagen")
                        .HasColumnType("image");

                    b.Property<decimal>("Iva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5, 2)")
                        .HasDefaultValueSql("((0.00))");

                    b.Property<string>("ModificadoPor")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<decimal>("PrecioCosto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValueSql("((0.00))");

                    b.Property<decimal>("PrecioVenta")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("Proveedor")
                        .HasColumnType("int");

                    b.Property<bool>("Servicio")
                        .HasColumnType("bit");

                    b.Property<decimal>("StockMinimo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18, 2)")
                        .HasDefaultValueSql("((0.00))");

                    b.Property<int>("SubLinea")
                        .HasColumnType("int");

                    b.Property<int>("UnidadMedida")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Proveedor");

                    b.HasIndex("SubLinea");

                    b.HasIndex("UnidadMedida");

                    b.HasIndex("Establecimiento", "Codigo", "Cancelado")
                        .IsUnique()
                        .HasDatabaseName("IX_Producto");

                    b.ToTable("Producto");
                });

            modelBuilder.Entity("GoldBusiness.Models.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BicoSwift")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<bool>("Cancelado")
                        .HasColumnType("bit");

                    b.Property<string>("CodPostal")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Email1")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("email1");

                    b.Property<string>("Email2")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("email2");

                    b.Property<string>("Fax1")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Fax2")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaHoraCreado")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("FechaHoraModificado")
                        .HasColumnType("datetime");

                    b.Property<string>("Iban")
                        .HasMaxLength(27)
                        .HasColumnType("nvarchar(27)");

                    b.Property<decimal>("Iva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(4, 2)")
                        .HasDefaultValueSql("((0.00))");

                    b.Property<string>("ModificadoPor")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Municipio")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nif")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Provincia")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telefono1")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telefono2")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Web")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo", "Cancelado")
                        .IsUnique()
                        .HasDatabaseName("IX_Proveedor");

                    b.ToTable("Proveedor");
                });

            modelBuilder.Entity("GoldBusiness.Models.Saldo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Existencia")
                        .HasColumnType("numeric(18, 2)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime");

                    b.Property<int>("Localidad")
                        .HasColumnType("int");

                    b.Property<int>("Producto")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Localidad");

                    b.HasIndex("Producto");

                    b.ToTable("Saldo");
                });

            modelBuilder.Entity("GoldBusiness.Models.SaldoAnterior", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Existencia")
                        .HasColumnType("numeric(18, 3)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime");

                    b.Property<decimal>("ImporteCosto")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("Localidad")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioCosto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValueSql("((0.00))");

                    b.Property<int>("Producto")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Localidad");

                    b.HasIndex("Producto");

                    b.ToTable("SaldoAnterior");
                });

            modelBuilder.Entity("GoldBusiness.Models.SubGrupoCuenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Cancelado")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("Deudora")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaHoraCreado")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("FechaHoraModificado")
                        .HasColumnType("datetime");

                    b.Property<int>("GrupoCuenta")
                        .HasColumnType("int");

                    b.Property<string>("ModificadoPor")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("GrupoCuenta");

                    b.HasIndex("Codigo", "GrupoCuenta", "Cancelado")
                        .IsUnique()
                        .HasDatabaseName("IX_SubGrupoCuenta");

                    b.ToTable("SubGrupoCuenta");
                });

            modelBuilder.Entity("GoldBusiness.Models.SubLinea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Cancelado")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("FechaHoraCreado")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("FechaHoraModificado")
                        .HasColumnType("datetime");

                    b.Property<int>("Linea")
                        .HasColumnType("int");

                    b.Property<string>("ModificadoPor")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Linea");

                    b.HasIndex("Codigo", "Linea", "Cancelado")
                        .IsUnique()
                        .HasDatabaseName("IX_SubLinea");

                    b.ToTable("SubLinea");
                });

            modelBuilder.Entity("GoldBusiness.Models.Transaccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Transaccion");
                });

            modelBuilder.Entity("GoldBusiness.Models.UnidadMedida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Cancelado")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("FechaHoraCreado")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("FechaHoraModificado")
                        .HasColumnType("datetime");

                    b.Property<string>("ModificadoPor")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo", "Cancelado")
                        .IsUnique()
                        .HasDatabaseName("IX_UnidadMedida");

                    b.ToTable("UnidadMedida");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GoldBusiness.Models.CajaRegistradora", b =>
                {
                    b.HasOne("GoldBusiness.Models.IdTurno", "IdTurnoNavigation")
                        .WithMany("CajaRegistradora")
                        .HasForeignKey("IdTurno")
                        .IsRequired()
                        .HasConstraintName("FK_CajaRegistradora_IdTurno");

                    b.Navigation("IdTurnoNavigation");
                });

            modelBuilder.Entity("GoldBusiness.Models.CajaRegistradoraDetalle", b =>
                {
                    b.HasOne("GoldBusiness.Models.CajaRegistradora", "CajaRegistradoraNavigation")
                        .WithMany("CajaRegistradoraDetalle")
                        .HasForeignKey("CajaRegistradora")
                        .IsRequired()
                        .HasConstraintName("FK_CajaRegistradoraDetalle_CajaRegistradora");

                    b.Navigation("CajaRegistradoraNavigation");
                });

            modelBuilder.Entity("GoldBusiness.Models.Comprobante", b =>
                {
                    b.HasOne("GoldBusiness.Models.Establecimiento", "EstablecimientoNavigation")
                        .WithMany("Comprobante")
                        .HasForeignKey("Establecimiento")
                        .IsRequired()
                        .HasConstraintName("FK_Comprobante_Establecimiento");

                    b.Navigation("EstablecimientoNavigation");
                });

            modelBuilder.Entity("GoldBusiness.Models.ComprobanteDetalle", b =>
                {
                    b.HasOne("GoldBusiness.Models.Comprobante", "ComprobanteNavigation")
                        .WithMany("ComprobanteDetalle")
                        .HasForeignKey("Comprobante")
                        .IsRequired()
                        .HasConstraintName("FK_ComprobanteDetalle_Comprobante");

                    b.HasOne("GoldBusiness.Models.Cuenta", "CuentaNavigation")
                        .WithMany("ComprobanteDetalle")
                        .HasForeignKey("Cuenta")
                        .IsRequired()
                        .HasConstraintName("FK_ComprobanteDetalle_Cuenta");

                    b.Navigation("ComprobanteNavigation");

                    b.Navigation("CuentaNavigation");
                });

            modelBuilder.Entity("GoldBusiness.Models.ComprobanteTemporal", b =>
                {
                    b.HasOne("GoldBusiness.Models.Establecimiento", "EstablecimientoNavigation")
                        .WithMany("ComprobanteTemporal")
                        .HasForeignKey("Establecimiento")
                        .IsRequired()
                        .HasConstraintName("FK_ComprobanteTemporal_Establecimiento");

                    b.Navigation("EstablecimientoNavigation");
                });

            modelBuilder.Entity("GoldBusiness.Models.ConceptoAjuste", b =>
                {
                    b.HasOne("GoldBusiness.Models.Cuenta", "CuentaNavigation")
                        .WithMany("ConceptoAjuste")
                        .HasForeignKey("Cuenta")
                        .IsRequired()
                        .HasConstraintName("FK_ConceptoAjuste_Cuenta");

                    b.Navigation("CuentaNavigation");
                });

            modelBuilder.Entity("GoldBusiness.Models.Configuracion", b =>
                {
                    b.HasOne("GoldBusiness.Models.Cuenta", "CuentaCobrarNavigation")
                        .WithMany("ConfiguracionCuentaCobrarNavigation")
                        .HasForeignKey("CuentaCobrar")
                        .IsRequired()
                        .HasConstraintName("FK_ConfiguracionCobrar_Cuenta");

                    b.HasOne("GoldBusiness.Models.Cuenta", "CuentaPagarNavigation")
                        .WithMany("ConfiguracionCuentaPagarNavigation")
                        .HasForeignKey("CuentaPagar")
                        .IsRequired()
                        .HasConstraintName("FK_ConfiguracionPagar_Cuenta");

                    b.Navigation("CuentaCobrarNavigation");

                    b.Navigation("CuentaPagarNavigation");
                });

            modelBuilder.Entity("GoldBusiness.Models.Cuenta", b =>
                {
                    b.HasOne("GoldBusiness.Models.SubGrupoCuenta", "SubGrupoCuentaNavigation")
                        .WithMany("Cuenta")
                        .HasForeignKey("SubGrupoCuenta")
                        .IsRequired()
                        .HasConstraintName("FK_Cuenta_SubGrupoCuenta");

                    b.Navigation("SubGrupoCuentaNavigation");
                });

            modelBuilder.Entity("GoldBusiness.Models.CuentaCobrarPagar", b =>
                {
                    b.HasOne("GoldBusiness.Models.Cliente", "ClienteNavigation")
                        .WithMany("CuentaCobrarPagar")
                        .HasForeignKey("Cliente")
                        .HasConstraintName("FK_CuentaCobrarPagar_Cliente");

                    b.HasOne("GoldBusiness.Models.Cuenta", "CuentaCobroNavigation")
                        .WithMany("CuentaCobrarPagarCuentaCobroNavigation")
                        .HasForeignKey("CuentaCobro")
                        .HasConstraintName("FK_CuentaCobrarPagar_CuentaCobro");

                    b.HasOne("GoldBusiness.Models.Cuenta", "CuentaPagoNavigation")
                        .WithMany("CuentaCobrarPagarCuentaPagoNavigation")
                        .HasForeignKey("CuentaPago")
                        .HasConstraintName("FK_CuentaCobrarPagar_CuentaPago");

                    b.HasOne("GoldBusiness.Models.Localidad", "LocalidadNavigation")
                        .WithMany("CuentaCobrarPagar")
                        .HasForeignKey("Localidad")
                        .HasConstraintName("FK_CuentaCobrarPagar_Localidad");

                    b.HasOne("GoldBusiness.Models.Proveedor", "ProveedorNavigation")
                        .WithMany("CuentaCobrarPagar")
                        .HasForeignKey("Proveedor")
                        .HasConstraintName("FK_CuentaCobrarPagar_Proveedor");

                    b.HasOne("GoldBusiness.Models.Transaccion", "TransaccionNavigation")
                        .WithMany("CuentaCobrarPagar")
                        .HasForeignKey("Transaccion")
                        .IsRequired()
                        .HasConstraintName("FK_CuentaCobrarPagar_Transaccion");

                    b.Navigation("ClienteNavigation");

                    b.Navigation("CuentaCobroNavigation");

                    b.Navigation("CuentaPagoNavigation");

                    b.Navigation("LocalidadNavigation");

                    b.Navigation("ProveedorNavigation");

                    b.Navigation("TransaccionNavigation");
                });

            modelBuilder.Entity("GoldBusiness.Models.Establecimiento", b =>
                {
                    b.HasOne("GoldBusiness.Models.Configuracion", "NegocioNavigation")
                        .WithMany("Establecimiento")
                        .HasForeignKey("Negocio")
                        .IsRequired()
                        .HasConstraintName("FK_Establecimiento_Configuracion");

                    b.Navigation("NegocioNavigation");
                });

            modelBuilder.Entity("GoldBusiness.Models.EstadoCuenta", b =>
                {
                    b.HasOne("GoldBusiness.Models.Cuenta", "CuentaNavigation")
                        .WithMany("EstadoCuenta")
                        .HasForeignKey("Cuenta")
                        .IsRequired()
                        .HasConstraintName("FK_EstadoCuenta_Cuenta");

                    b.HasOne("GoldBusiness.Models.Establecimiento", "EstablecimientoNavigation")
                        .WithMany("EstadoCuenta")
                        .HasForeignKey("Establecimiento")
                        .IsRequired()
                        .HasConstraintName("FK_EstadoCuenta_Establecimiento");

                    b.Navigation("CuentaNavigation");

                    b.Navigation("EstablecimientoNavigation");
                });

            modelBuilder.Entity("GoldBusiness.Models.FichaProducto", b =>
                {
                    b.HasOne("GoldBusiness.Models.Producto", "CodigoNavigation")
                        .WithMany("FichaProductoCodigoNavigation")
                        .HasForeignKey("Codigo")
                        .IsRequired()
                        .HasConstraintName("FK_FichaProducto_Producto1");

                    b.HasOne("GoldBusiness.Models.Localidad", "LocalidadNavigation")
                        .WithMany("FichaProducto")
                        .HasForeignKey("Localidad")
                        .IsRequired()
                        .HasConstraintName("FK_FichaProducto_Localidad");

                    b.HasOne("GoldBusiness.Models.Producto", "ProductoNavigation")
                        .WithMany("FichaProductoProductoNavigation")
                        .HasForeignKey("Producto")
                        .IsRequired()
                        .HasConstraintName("FK_FichaProducto_Producto");

                    b.Navigation("CodigoNavigation");

                    b.Navigation("LocalidadNavigation");

                    b.Navigation("ProductoNavigation");
                });

            modelBuilder.Entity("GoldBusiness.Models.Localidad", b =>
                {
                    b.HasOne("GoldBusiness.Models.Cuenta", "CuentaCostoNavigation")
                        .WithMany("LocalidadCuentaCostoNavigation")
                        .HasForeignKey("CuentaCosto")
                        .IsRequired()
                        .HasConstraintName("FK_Localidad_CuentaCosto");

                    b.HasOne("GoldBusiness.Models.Cuenta", "CuentaDevolucionNavigation")
                        .WithMany("LocalidadCuentaDevolucionNavigation")
                        .HasForeignKey("CuentaDevolucion")
                        .IsRequired()
                        .HasConstraintName("FK_Localidad_CuentaDevolucion");

                    b.HasOne("GoldBusiness.Models.Cuenta", "CuentaInventarioNavigation")
                        .WithMany("LocalidadCuentaInventarioNavigation")
                        .HasForeignKey("CuentaInventario")
                        .IsRequired()
                        .HasConstraintName("FK_Localidad_CuentaInventario");

                    b.HasOne("GoldBusiness.Models.Cuenta", "CuentaVentaNavigation")
                        .WithMany("LocalidadCuentaVentaNavigation")
                        .HasForeignKey("CuentaVenta")
                        .IsRequired()
                        .HasConstraintName("FK_Localidad_CuentaVenta");

                    b.HasOne("GoldBusiness.Models.Establecimiento", "EstablecimientoNavigation")
                        .WithMany("Localidad")
                        .HasForeignKey("Establecimiento")
                        .IsRequired()
                        .HasConstraintName("FK_Localidad_Establecimiento");

                    b.Navigation("CuentaCostoNavigation");

                    b.Navigation("CuentaDevolucionNavigation");

                    b.Navigation("CuentaInventarioNavigation");

                    b.Navigation("CuentaVentaNavigation");

                    b.Navigation("EstablecimientoNavigation");
                });

            modelBuilder.Entity("GoldBusiness.Models.Moneda", b =>
                {
                    b.HasOne("GoldBusiness.Models.Establecimiento", "EstablecimientoNavigation")
                        .WithMany("Moneda")
                        .HasForeignKey("Establecimiento")
                        .IsRequired()
                        .HasConstraintName("FK_Moneda_Establecimiento");

                    b.Navigation("EstablecimientoNavigation");
                });

            modelBuilder.Entity("GoldBusiness.Models.OperacionesDetalle", b =>
                {
                    b.HasOne("GoldBusiness.Models.Producto", "CodigoNavigation")
                        .WithMany("OperacionesDetalle")
                        .HasForeignKey("Codigo")
                        .IsRequired()
                        .HasConstraintName("FK_OperacionesDetalle_Producto");

                    b.HasOne("GoldBusiness.Models.Localidad", "LocalidadNavigation")
                        .WithMany("OperacionesDetalle")
                        .HasForeignKey("Localidad")
                        .IsRequired()
                        .HasConstraintName("FK_OperacionesDetalle_Localidad");

                    b.HasOne("GoldBusiness.Models.OperacionesEncabezado", "OperacionEncabezadoNavigation")
                        .WithMany("OperacionesDetalle")
                        .HasForeignKey("OperacionesEncabezado")
                        .IsRequired()
                        .HasConstraintName("FK_OperacionesDetalle_OperacionesEncabezado");

                    b.Navigation("CodigoNavigation");

                    b.Navigation("LocalidadNavigation");

                    b.Navigation("OperacionEncabezadoNavigation");
                });

            modelBuilder.Entity("GoldBusiness.Models.OperacionesEncabezado", b =>
                {
                    b.HasOne("GoldBusiness.Models.Cliente", "ClienteNavigation")
                        .WithMany("OperacionesEncabezado")
                        .HasForeignKey("Cliente")
                        .HasConstraintName("FK_OperacionesEncabezado_Cliente");

                    b.HasOne("GoldBusiness.Models.ConceptoAjuste", "ConceptoAjusteNavigation")
                        .WithMany("OperacionesEncabezado")
                        .HasForeignKey("ConceptoAjuste")
                        .HasConstraintName("FK_OperacionesEncabezado_ConceptoAjuste");

                    b.HasOne("GoldBusiness.Models.Establecimiento", "EstablecimientoNavigation")
                        .WithMany("OperacionesEncabezado")
                        .HasForeignKey("Establecimiento")
                        .IsRequired()
                        .HasConstraintName("FK_OperacionesEncabezado_Establecimiento");

                    b.HasOne("GoldBusiness.Models.Proveedor", "ProveedorNavigation")
                        .WithMany("OperacionesEncabezado")
                        .HasForeignKey("Proveedor")
                        .HasConstraintName("FK_OperacionesEncabezado_Proveedor");

                    b.HasOne("GoldBusiness.Models.Transaccion", "TransaccionNavigation")
                        .WithMany("OperacionesEncabezado")
                        .HasForeignKey("Transaccion")
                        .IsRequired()
                        .HasConstraintName("FK_OperacionesEncabezado_Transaccion");

                    b.Navigation("ClienteNavigation");

                    b.Navigation("ConceptoAjusteNavigation");

                    b.Navigation("EstablecimientoNavigation");

                    b.Navigation("ProveedorNavigation");

                    b.Navigation("TransaccionNavigation");
                });

            modelBuilder.Entity("GoldBusiness.Models.OperacionesServicio", b =>
                {
                    b.HasOne("GoldBusiness.Models.OperacionesDetalle", "OperacionesDetalleNavigation")
                        .WithMany("OperacionesServicio")
                        .HasForeignKey("OperacionesDetalle")
                        .IsRequired()
                        .HasConstraintName("FK_OperacionesServicio_OperacionesDetalle");

                    b.Navigation("OperacionesDetalleNavigation");
                });

            modelBuilder.Entity("GoldBusiness.Models.Producto", b =>
                {
                    b.HasOne("GoldBusiness.Models.Establecimiento", "EstablecimientoNavigation")
                        .WithMany("Producto")
                        .HasForeignKey("Establecimiento")
                        .IsRequired()
                        .HasConstraintName("FK_Producto_Establecimiento");

                    b.HasOne("GoldBusiness.Models.Proveedor", "ProveedorNavigation")
                        .WithMany("Producto")
                        .HasForeignKey("Proveedor")
                        .IsRequired()
                        .HasConstraintName("FK_Producto_Proveedor");

                    b.HasOne("GoldBusiness.Models.SubLinea", "SubLineaNavigation")
                        .WithMany("Producto")
                        .HasForeignKey("SubLinea")
                        .IsRequired()
                        .HasConstraintName("FK_Producto_SubLinea");

                    b.HasOne("GoldBusiness.Models.UnidadMedida", "UnidadMedidaNavigation")
                        .WithMany("Producto")
                        .HasForeignKey("UnidadMedida")
                        .IsRequired()
                        .HasConstraintName("FK_Producto_UnidadMedida");

                    b.Navigation("EstablecimientoNavigation");

                    b.Navigation("ProveedorNavigation");

                    b.Navigation("SubLineaNavigation");

                    b.Navigation("UnidadMedidaNavigation");
                });

            modelBuilder.Entity("GoldBusiness.Models.Saldo", b =>
                {
                    b.HasOne("GoldBusiness.Models.Localidad", "LocalidadNavigation")
                        .WithMany("Saldo")
                        .HasForeignKey("Localidad")
                        .IsRequired()
                        .HasConstraintName("FK_Saldo_Localidad");

                    b.HasOne("GoldBusiness.Models.Producto", "ProductoNavigation")
                        .WithMany("Saldo")
                        .HasForeignKey("Producto")
                        .IsRequired()
                        .HasConstraintName("FK_Saldo_Producto");

                    b.Navigation("LocalidadNavigation");

                    b.Navigation("ProductoNavigation");
                });

            modelBuilder.Entity("GoldBusiness.Models.SaldoAnterior", b =>
                {
                    b.HasOne("GoldBusiness.Models.Localidad", "LocalidadNavigation")
                        .WithMany("SaldoAnterior")
                        .HasForeignKey("Localidad")
                        .IsRequired()
                        .HasConstraintName("FK_SaldoAnterior_Localidad");

                    b.HasOne("GoldBusiness.Models.Producto", "ProductoNavigation")
                        .WithMany("SaldoAnterior")
                        .HasForeignKey("Producto")
                        .IsRequired()
                        .HasConstraintName("FK_SaldoAnterior_Producto");

                    b.Navigation("LocalidadNavigation");

                    b.Navigation("ProductoNavigation");
                });

            modelBuilder.Entity("GoldBusiness.Models.SubGrupoCuenta", b =>
                {
                    b.HasOne("GoldBusiness.Models.GrupoCuenta", "GrupoCuentaNavigation")
                        .WithMany("SubGrupoCuenta")
                        .HasForeignKey("GrupoCuenta")
                        .IsRequired()
                        .HasConstraintName("FK_SubGrupoCuenta_GrupoCuenta");

                    b.Navigation("GrupoCuentaNavigation");
                });

            modelBuilder.Entity("GoldBusiness.Models.SubLinea", b =>
                {
                    b.HasOne("GoldBusiness.Models.Linea", "LineaNavigation")
                        .WithMany("SubLinea")
                        .HasForeignKey("Linea")
                        .IsRequired()
                        .HasConstraintName("FK_SubLinea_Linea");

                    b.Navigation("LineaNavigation");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("GoldBusiness.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("GoldBusiness.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GoldBusiness.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("GoldBusiness.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GoldBusiness.Models.CajaRegistradora", b =>
                {
                    b.Navigation("CajaRegistradoraDetalle");
                });

            modelBuilder.Entity("GoldBusiness.Models.Cliente", b =>
                {
                    b.Navigation("CuentaCobrarPagar");

                    b.Navigation("OperacionesEncabezado");
                });

            modelBuilder.Entity("GoldBusiness.Models.Comprobante", b =>
                {
                    b.Navigation("ComprobanteDetalle");
                });

            modelBuilder.Entity("GoldBusiness.Models.ConceptoAjuste", b =>
                {
                    b.Navigation("OperacionesEncabezado");
                });

            modelBuilder.Entity("GoldBusiness.Models.Configuracion", b =>
                {
                    b.Navigation("Establecimiento");
                });

            modelBuilder.Entity("GoldBusiness.Models.Cuenta", b =>
                {
                    b.Navigation("ComprobanteDetalle");

                    b.Navigation("ConceptoAjuste");

                    b.Navigation("ConfiguracionCuentaCobrarNavigation");

                    b.Navigation("ConfiguracionCuentaPagarNavigation");

                    b.Navigation("CuentaCobrarPagarCuentaCobroNavigation");

                    b.Navigation("CuentaCobrarPagarCuentaPagoNavigation");

                    b.Navigation("EstadoCuenta");

                    b.Navigation("LocalidadCuentaCostoNavigation");

                    b.Navigation("LocalidadCuentaDevolucionNavigation");

                    b.Navigation("LocalidadCuentaInventarioNavigation");

                    b.Navigation("LocalidadCuentaVentaNavigation");
                });

            modelBuilder.Entity("GoldBusiness.Models.Establecimiento", b =>
                {
                    b.Navigation("Comprobante");

                    b.Navigation("ComprobanteTemporal");

                    b.Navigation("EstadoCuenta");

                    b.Navigation("Localidad");

                    b.Navigation("Moneda");

                    b.Navigation("OperacionesEncabezado");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("GoldBusiness.Models.GrupoCuenta", b =>
                {
                    b.Navigation("SubGrupoCuenta");
                });

            modelBuilder.Entity("GoldBusiness.Models.IdTurno", b =>
                {
                    b.Navigation("CajaRegistradora");
                });

            modelBuilder.Entity("GoldBusiness.Models.Linea", b =>
                {
                    b.Navigation("SubLinea");
                });

            modelBuilder.Entity("GoldBusiness.Models.Localidad", b =>
                {
                    b.Navigation("CuentaCobrarPagar");

                    b.Navigation("FichaProducto");

                    b.Navigation("OperacionesDetalle");

                    b.Navigation("Saldo");

                    b.Navigation("SaldoAnterior");
                });

            modelBuilder.Entity("GoldBusiness.Models.OperacionesDetalle", b =>
                {
                    b.Navigation("OperacionesServicio");
                });

            modelBuilder.Entity("GoldBusiness.Models.OperacionesEncabezado", b =>
                {
                    b.Navigation("OperacionesDetalle");
                });

            modelBuilder.Entity("GoldBusiness.Models.Producto", b =>
                {
                    b.Navigation("FichaProductoCodigoNavigation");

                    b.Navigation("FichaProductoProductoNavigation");

                    b.Navigation("OperacionesDetalle");

                    b.Navigation("Saldo");

                    b.Navigation("SaldoAnterior");
                });

            modelBuilder.Entity("GoldBusiness.Models.Proveedor", b =>
                {
                    b.Navigation("CuentaCobrarPagar");

                    b.Navigation("OperacionesEncabezado");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("GoldBusiness.Models.SubGrupoCuenta", b =>
                {
                    b.Navigation("Cuenta");
                });

            modelBuilder.Entity("GoldBusiness.Models.SubLinea", b =>
                {
                    b.Navigation("Producto");
                });

            modelBuilder.Entity("GoldBusiness.Models.Transaccion", b =>
                {
                    b.Navigation("CuentaCobrarPagar");

                    b.Navigation("OperacionesEncabezado");
                });

            modelBuilder.Entity("GoldBusiness.Models.UnidadMedida", b =>
                {
                    b.Navigation("Producto");
                });
#pragma warning restore 612, 618
        }
    }
}
